### ISSUE TITLE
Improve scalability and privacy of Likes and Following

### ISSUE THREAD

**Issue by kenara** [codewired/FriendlyPix-Updated#2]
As noted in comments in FirebaseHelper.js, `registerForLikesCount()` and `registerForFollowersCount()` won't scale well if there are lots of likes or follows.

I got an informative answer from @puf when I asked about this here [https://stackoverflow.com/questions/60136729/scalability-of-numchildren-function-in-firebase-realtime-database](url)

This code sample [https://github.com/firebase/functions-samples/blob/master/child-count/functions/index.js](https://github.com/firebase/functions-samples/blob/master/child-count/functions/index.js) shows how this can be handled, and I've implemented it in my fork here: [https://github.com/kenara/FriendlyPix-Updated/blob/master/src/FirebaseHelper.js#L714](https://github.com/kenara/FriendlyPix-Updated/blob/master/src/FirebaseHelper.js#L714) with a corresponding function here:
[https://github.com/kenara/FriendlyPix-Updated/blob/master/functions/likeCount.js](url)

The function updates a new /liked node with the count. 

Also, liking in Friendlypix is understood by users to be anonymous. My friendlypix-inspired site is a job board, and who favorites a job needs to be private. With the above arrangement I could set the rule for "likes": ".read" to false.

**Comment by codewired** [comment]
Will review and update accordingly, thanks for the insight. Well done.

**Comment by kenara** [comment]
Thanks for this. To be clear, I have never managed to capture the web
sockets data that would include these user ids, but some people know how to
do this. And I wouldn't want any users to end up in jail for liking a
controversial post...
